/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.payoutsimulator;

import java.awt.EventQueue;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.Observable;
import java.util.Observer;

import javafx.embed.swing.JFXPanel;

import javax.swing.ImageIcon;

import at.metalab.payoutsim.Kassomat;
import at.metalab.payoutsim.Simulations;

/**
 *
 * @author hetti
 */
public class PayoutFrame extends javax.swing.JFrame {

	private Kassomat kassomat;

	public void setKassomat(Kassomat kassomat) {
		this.kassomat = kassomat;
	}

	/**
	 * Creates new form PayoutSim
	 */
	public PayoutFrame() {
		initComponents();
		this.setCursor(Toolkit.getDefaultToolkit().createCustomCursor(
				new ImageIcon(Thread.currentThread().getContextClassLoader()
						.getResource("beutel.gif")).getImage(),
				new Point(0, 0), "custom cursor"));

		textField1.setText("#1");
		textField2.setText("#2");
		textField3.setText("#3");
		textField4.setText("#4");
		textField5.setText("#5");
		textField6.setText("#6");
		textField7.setText("#7");
		textField8.setText("#8"); // 10c
		textField9.setText("#9"); // 20c
		textField10.setText("#10"); // 50c
		textField11.setText("#11"); // 1e
		textField12.setText("#12"); // 2e

		EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				Observer observer = new Observer() {

					@Override
					public void update(Observable o, Object arg) {
						textField8.setText(String.valueOf(kassomat
								.getHopperMonies().getAmount(1))); // 10c
						textField8.repaint();

						textField9.setText(String.valueOf(kassomat
								.getHopperMonies().getAmount(2))); // 20c
						textField9.repaint();

						textField10.setText(String.valueOf(kassomat
								.getHopperMonies().getAmount(3))); // 50c
						textField10.repaint();

						textField11.setText(String.valueOf(kassomat
								.getHopperMonies().getAmount(4))); // 1e
						textField11.repaint();

						textField12.setText(String.valueOf(kassomat
								.getHopperMonies().getAmount(5))); // 2e
						textField12.repaint();

						// notes
						textField1.setText(String.valueOf(kassomat
								.getValidatorMonies().getAmount(1))); // 10c
						textField1.repaint();

						textField2.setText(String.valueOf(kassomat
								.getValidatorMonies().getAmount(2))); // 20c
						textField2.repaint();

						textField3.setText(String.valueOf(kassomat
								.getValidatorMonies().getAmount(3))); // 50c
						textField3.repaint();

						textField4.setText(String.valueOf(kassomat
								.getValidatorMonies().getAmount(4))); // 1e
						textField4.repaint();

						textField5.setText(String.valueOf(kassomat
								.getValidatorMonies().getAmount(5))); // 1e
						textField5.repaint();

						textField6.setText(String.valueOf(kassomat
								.getValidatorMonies().getAmount(6))); // 2e
						textField6.repaint();

						textField7.setText(String.valueOf(kassomat
								.getValidatorMonies().getAmount(7))); // 2e
						textField7.repaint();
					}
				};

				observer.update(null, null); // dirty hack

				kassomat.getValidatorMonies().getMoneyChange()
						.addObserver(observer);
				kassomat.getHopperMonies().getMoneyChange()
						.addObserver(observer);
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox<>();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox<>();
		jButton2 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		textField1 = new java.awt.TextField();
		textField2 = new java.awt.TextField();
		textField3 = new java.awt.TextField();
		textField4 = new java.awt.TextField();
		textField5 = new java.awt.TextField();
		textField6 = new java.awt.TextField();
		textField7 = new java.awt.TextField();
		jButton7 = new javax.swing.JButton();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		textField8 = new java.awt.TextField();
		textField9 = new java.awt.TextField();
		textField10 = new java.awt.TextField();
		textField11 = new java.awt.TextField();
		textField12 = new java.awt.TextField();
		jButton9 = new javax.swing.JButton();
		jLabel19 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		jButton8 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Legendary Money Simulator with some Fairydust™");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jButton1.setText("Input Paper Money");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
		jLabel1.setText("How much Paper Money $$$ ?");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "5", "10", "20", "50", "100", "200" }));

		jLabel2.setText("Euro");

		jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
		jLabel3.setText("How much Coin $$$ ?");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "10", "20", "50", "1", "2" }));

		jButton2.setText("Input Coin");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel4.setText("cent / €");

		jButton3.setText("Reject Money");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("Input invalid Note");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setText("Power On");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setText("Power Off");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jLabel5.setText("x 5€");

		jLabel6.setText("x 10€");

		jLabel7.setText("x 20€");

		jLabel8.setText("x 50€");

		jLabel9.setText("x 100€");

		jLabel10.setText("x 200€");

		jLabel11.setText("x 500€");

		textField1.setText("0");
		textField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				textField1ActionPerformed(evt);
			}
		});

		textField2.setText("0");

		textField3.setText("0");
		textField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				textField3ActionPerformed(evt);
			}
		});

		textField4.setText("0");

		textField5.setText("0");

		textField6.setText("0");

		textField7.setText("0");

		jButton7.setText("Add Money");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jLabel12.setText("Paper Money");

		jLabel13.setText("Coins");

		jLabel14.setText("x 10c");

		jLabel15.setText("x 20c");

		jLabel16.setText("x 50c");

		jLabel17.setText("x 1€");

		jLabel18.setText("x 2€");

		textField8.setText("0");

		textField9.setText("0");

		textField10.setText("0");

		textField11.setText("0");

		textField12.setText("0");

		jButton9.setText("Cashbox removed");

		jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
		jLabel19.setText("Magic Money Adder™");
		jLabel19.setToolTipText("");

		jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/money.jpeg"))); // NOI18N

		jButton8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
		jButton8.setText("Shredder your $$$ !™");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jLabel3)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(6,
																										6,
																										6)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jButton9)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jButton4)
																																				.addComponent(
																																						jButton3))
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jButton6,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						88,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)
																																				.addComponent(
																																						jButton5,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						88,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)))))))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(42, 42,
																		42)
																.addComponent(
																		jComboBox1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jLabel2))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(26, 26,
																		26)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(12,
																										12,
																										12)
																								.addComponent(
																										jButton2))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jComboBox2,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										jLabel4))))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(25, 25,
																		25)
																.addComponent(
																		jButton1)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										20, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel21)
																								.addGap(73,
																										73,
																										73)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.TRAILING)
																																				.addGroup(
																																						javax.swing.GroupLayout.Alignment.LEADING,
																																						layout.createSequentialGroup()
																																								.addComponent(
																																										textField12,
																																										javax.swing.GroupLayout.PREFERRED_SIZE,
																																										31,
																																										javax.swing.GroupLayout.PREFERRED_SIZE)
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																								.addComponent(
																																										jLabel18))
																																				.addGroup(
																																						javax.swing.GroupLayout.Alignment.LEADING,
																																						layout.createSequentialGroup()
																																								.addComponent(
																																										textField11,
																																										javax.swing.GroupLayout.PREFERRED_SIZE,
																																										31,
																																										javax.swing.GroupLayout.PREFERRED_SIZE)
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																								.addComponent(
																																										jLabel17))
																																				.addGroup(
																																						javax.swing.GroupLayout.Alignment.LEADING,
																																						layout.createSequentialGroup()
																																								.addComponent(
																																										textField10,
																																										javax.swing.GroupLayout.PREFERRED_SIZE,
																																										31,
																																										javax.swing.GroupLayout.PREFERRED_SIZE)
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																								.addComponent(
																																										jLabel16))
																																				.addGroup(
																																						javax.swing.GroupLayout.Alignment.LEADING,
																																						layout.createSequentialGroup()
																																								.addComponent(
																																										textField9,
																																										javax.swing.GroupLayout.PREFERRED_SIZE,
																																										31,
																																										javax.swing.GroupLayout.PREFERRED_SIZE)
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																								.addComponent(
																																										jLabel15))
																																				.addGroup(
																																						layout.createSequentialGroup()
																																								.addComponent(
																																										textField8,
																																										javax.swing.GroupLayout.PREFERRED_SIZE,
																																										31,
																																										javax.swing.GroupLayout.PREFERRED_SIZE)
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																								.addComponent(
																																										jLabel14)))
																																.addGap(18,
																																		18,
																																		18))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel13)
																																.addGap(39,
																																		39,
																																		39)))
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel12)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				false)
																																				.addComponent(
																																						textField2,
																																						javax.swing.GroupLayout.Alignment.TRAILING,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						textField3,
																																						javax.swing.GroupLayout.Alignment.TRAILING,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						textField4,
																																						javax.swing.GroupLayout.Alignment.TRAILING,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						textField7,
																																						javax.swing.GroupLayout.Alignment.TRAILING,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						textField6,
																																						javax.swing.GroupLayout.Alignment.TRAILING,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						textField5,
																																						javax.swing.GroupLayout.Alignment.TRAILING,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						textField1,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						30,
																																						javax.swing.GroupLayout.PREFERRED_SIZE))
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jLabel5)
																																				.addComponent(
																																						jLabel6)
																																				.addComponent(
																																						jLabel7)
																																				.addComponent(
																																						jLabel8)
																																				.addComponent(
																																						jLabel9)
																																				.addComponent(
																																						jLabel10)
																																				.addComponent(
																																						jLabel11)))))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(29,
																										29,
																										29)
																								.addComponent(
																										jButton8)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)
																								.addComponent(
																										jButton7)
																								.addGap(61,
																										61,
																										61)))
																.addGap(9, 9, 9))
												.addComponent(
														jLabel19,
														javax.swing.GroupLayout.Alignment.TRAILING))
								.addGap(24, 24, 24)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(22, 22,
																		22)
																.addComponent(
																		jLabel1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jComboBox1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel2))
																.addGap(3, 3, 3)
																.addComponent(
																		jButton1)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jLabel3)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jComboBox2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel4))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton2)
																.addGap(24, 24,
																		24)
																.addComponent(
																		jButton9)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jButton4)
																				.addComponent(
																						jButton5))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jButton3)
																				.addComponent(
																						jButton6)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(24, 24,
																		24)
																.addComponent(
																		jLabel19)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														jLabel12)
																												.addComponent(
																														jLabel13))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jLabel5)
																																				.addComponent(
																																						textField1,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)
																																				.addGroup(
																																						layout.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																								.addComponent(
																																										textField8,
																																										javax.swing.GroupLayout.PREFERRED_SIZE,
																																										javax.swing.GroupLayout.DEFAULT_SIZE,
																																										javax.swing.GroupLayout.PREFERRED_SIZE)
																																								.addComponent(
																																										jLabel14)))
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addGroup(
																																						layout.createSequentialGroup()
																																								.addGroup(
																																										layout.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.LEADING)
																																												.addComponent(
																																														jLabel6)
																																												.addComponent(
																																														textField2,
																																														javax.swing.GroupLayout.PREFERRED_SIZE,
																																														javax.swing.GroupLayout.DEFAULT_SIZE,
																																														javax.swing.GroupLayout.PREFERRED_SIZE))
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																								.addComponent(
																																										jLabel7))
																																				.addGroup(
																																						layout.createSequentialGroup()
																																								.addGroup(
																																										layout.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.TRAILING)
																																												.addComponent(
																																														jLabel15,
																																														javax.swing.GroupLayout.PREFERRED_SIZE,
																																														17,
																																														javax.swing.GroupLayout.PREFERRED_SIZE)
																																												.addComponent(
																																														textField9,
																																														javax.swing.GroupLayout.PREFERRED_SIZE,
																																														javax.swing.GroupLayout.DEFAULT_SIZE,
																																														javax.swing.GroupLayout.PREFERRED_SIZE))
																																								.addGap(8,
																																										8,
																																										8)
																																								.addGroup(
																																										layout.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.LEADING)
																																												.addComponent(
																																														textField3,
																																														javax.swing.GroupLayout.PREFERRED_SIZE,
																																														javax.swing.GroupLayout.DEFAULT_SIZE,
																																														javax.swing.GroupLayout.PREFERRED_SIZE)
																																												.addComponent(
																																														textField10,
																																														javax.swing.GroupLayout.PREFERRED_SIZE,
																																														javax.swing.GroupLayout.DEFAULT_SIZE,
																																														javax.swing.GroupLayout.PREFERRED_SIZE)
																																												.addComponent(
																																														jLabel16))))
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addGroup(
																																						layout.createSequentialGroup()
																																								.addGroup(
																																										layout.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.LEADING)
																																												.addComponent(
																																														jLabel8)
																																												.addComponent(
																																														textField4,
																																														javax.swing.GroupLayout.PREFERRED_SIZE,
																																														javax.swing.GroupLayout.DEFAULT_SIZE,
																																														javax.swing.GroupLayout.PREFERRED_SIZE))
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																								.addGroup(
																																										layout.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.LEADING)
																																												.addComponent(
																																														textField5,
																																														javax.swing.GroupLayout.PREFERRED_SIZE,
																																														javax.swing.GroupLayout.DEFAULT_SIZE,
																																														javax.swing.GroupLayout.PREFERRED_SIZE)
																																												.addComponent(
																																														jLabel9)))
																																				.addGroup(
																																						layout.createSequentialGroup()
																																								.addGroup(
																																										layout.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.LEADING)
																																												.addComponent(
																																														textField11,
																																														javax.swing.GroupLayout.PREFERRED_SIZE,
																																														javax.swing.GroupLayout.DEFAULT_SIZE,
																																														javax.swing.GroupLayout.PREFERRED_SIZE)
																																												.addComponent(
																																														jLabel17))
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																								.addGroup(
																																										layout.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.LEADING)
																																												.addComponent(
																																														textField12,
																																														javax.swing.GroupLayout.PREFERRED_SIZE,
																																														javax.swing.GroupLayout.DEFAULT_SIZE,
																																														javax.swing.GroupLayout.PREFERRED_SIZE)
																																												.addGroup(
																																														javax.swing.GroupLayout.Alignment.TRAILING,
																																														layout.createSequentialGroup()
																																																.addComponent(
																																																		jLabel18)
																																																.addGap(2,
																																																		2,
																																																		2)))))
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		jLabel10))
																												.addComponent(
																														textField6,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														textField7,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jLabel11)))
																				.addComponent(
																						jLabel21))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jButton7)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(27,
																										27,
																										27)
																								.addComponent(
																										jButton8)))))
								.addContainerGap(21, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private static void playSound(String sample) {
		/*
		 * try { String strUri = Thread.currentThread().getContextClassLoader()
		 * .getResource(sample).toURI().toString(); Media sound = new
		 * Media(strUri); MediaPlayer mediaPlayer = new MediaPlayer(sound);
		 * mediaPlayer.play(); } catch (Exception exception) { // too bad
		 * exception.printStackTrace(); }
		 */
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		int papervalue = Integer
				.parseInt((String) jComboBox1.getSelectedItem());

		new Thread(new Runnable() {

			@Override
			public void run() {
				try {
					playSound("shredder.wav");

					int amount = papervalue * 100;
					Simulations.insertNote(kassomat, amount);
				} catch (InterruptedException interruptedException) {
					System.err.println("simulation interrupted");
				}
			}
		}).start();
		;
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		int coinvalue = Integer.parseInt((String) jComboBox2.getSelectedItem());

		new Thread(new Runnable() {

			@Override
			public void run() {
				try {
					playSound("smw_coin.wav");

					int amount = coinvalue; // coin value is in cents or euros
					if (amount == 1) {
						amount = 100;
					} else if (amount == 2) {
						amount = 200;
					}
					Simulations.insertCoin(kassomat, amount);
				} catch (InterruptedException interruptedException) {
					System.err.println("simulation interrupted");
				}
			}
		}).start();
		;
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		playSound("startup.wav");
		// TODO Coin Code
		int coinvalue = Integer.parseInt((String) jComboBox2.getSelectedItem());
	}// GEN-LAST:event_jButton5ActionPerformed

	private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_textField1ActionPerformed

	private void textField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textField3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_textField3ActionPerformed

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
		playSound("cashregister.wav");
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton7ActionPerformed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
		playSound("winxpshutdown.wav");
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton6ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		new Thread(new Runnable() {

			@Override
			public void run() {
				try {
					playSound("reject.wav");
					Simulations.rejectNote(kassomat);
				} catch (InterruptedException interruptedException) {
					System.err.println("simulation interrupted");
				}
			}
		}).start();
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		playSound("fail.wav");
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
		playSound("shredder.wav");
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton8ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PayoutFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PayoutFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PayoutFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PayoutFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		JFXPanel fxPanel = new JFXPanel();
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PayoutFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private java.awt.TextField textField1;
	private java.awt.TextField textField10;
	private java.awt.TextField textField11;
	private java.awt.TextField textField12;
	private java.awt.TextField textField2;
	private java.awt.TextField textField3;
	private java.awt.TextField textField4;
	private java.awt.TextField textField5;
	private java.awt.TextField textField6;
	private java.awt.TextField textField7;
	private java.awt.TextField textField8;
	private java.awt.TextField textField9;
	// End of variables declaration//GEN-END:variables

}
